//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package rpg.v4.middleware.jaxb;

import javax.xml.bind.annotation.*;
import java.io.Serializable;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Weight" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="UUID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{rgb.jaxb.character}V4_Weapon"/>
 *           &lt;element ref="{rgb.jaxb.character}V4_Item"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "weight",
    "uuid",
    "v4Weapon",
    "v4Item"
})
@XmlRootElement(name = "V4_ItemCapsule")
public class V4ItemCapsule implements Serializable {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Weight")
    protected double weight;
    @XmlElement(name = "UUID")
    protected String uuid;
    @XmlElement(name = "V4_Weapon")
    protected V4Weapon v4Weapon;
    @XmlElement(name = "V4_Item")
    protected V4Item v4Item;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     */
    public double getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     */
    public void setWeight(double value) {
        this.weight = value;
    }

    /**
     * Gets the value of the uuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUUID() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUUID(String value) {
        this.uuid = value;
    }

    /**
     * Gets the value of the v4Weapon property.
     * 
     * @return
     *     possible object is
     *     {@link V4Weapon }
     *     
     */
    public V4Weapon getV4Weapon() {
        return v4Weapon;
    }

    /**
     * Sets the value of the v4Weapon property.
     * 
     * @param value
     *     allowed object is
     *     {@link V4Weapon }
     *     
     */
    public void setV4Weapon(V4Weapon value) {
        this.v4Weapon = value;
    }

    /**
     * Gets the value of the v4Item property.
     * 
     * @return
     *     possible object is
     *     {@link V4Item }
     *     
     */
    public V4Item getV4Item() {
        return v4Item;
    }

    /**
     * Sets the value of the v4Item property.
     * 
     * @param value
     *     allowed object is
     *     {@link V4Item }
     *     
     */
    public void setV4Item(V4Item value) {
        this.v4Item = value;
    }

}
