//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package rpg.v4.middleware.jaxb;

import javax.xml.bind.annotation.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DisplayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Type">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Integer"/>
 *               &lt;enumeration value="String"/>
 *               &lt;enumeration value="IntegerAbility"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SubType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Ability"/>
 *               &lt;enumeration value="Skill"/>
 *               &lt;enumeration value="Defense"/>
 *               &lt;enumeration value="Untyped"/>
 *               &lt;enumeration value="Unique ID"/>
 *               &lt;enumeration value="Character Information"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Category">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Ability scores"/>
 *               &lt;enumeration value="Defenses"/>
 *               &lt;enumeration value="Skills"/>
 *               &lt;enumeration value="Movement"/>
 *               &lt;enumeration value="Senses"/>
 *               &lt;enumeration value="Other"/>
 *               &lt;enumeration value="Character information"/>
 *               &lt;enumeration value="Saving throws"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="InitialValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StateID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{rgb.jaxb.character}V4_ModifierTypeList" minOccurs="0"/>
 *         &lt;element ref="{rgb.jaxb.character}V4_StateID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{rgb.jaxb.character}V4_Function" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UserEntry" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Hidden" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "displayName",
    "type",
    "subType",
    "category",
    "initialValue",
    "stateID",
    "v4ModifierTypeList",
    "v4StateID",
    "v4Function",
    "userEntry",
    "hidden"
})
@XmlRootElement(name = "V4_State")
public class V4State implements Serializable {

    @XmlElement(name = "DisplayName", required = true)
    protected String displayName;
    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "SubType", required = true)
    protected String subType;
    @XmlElement(name = "Category", required = true)
    protected String category;
    @XmlElement(name = "InitialValue", required = true)
    protected String initialValue;
    @XmlElement(name = "StateID", required = true)
    protected String stateID;
    @XmlElement(name = "V4_ModifierTypeList")
    protected V4ModifierTypeList v4ModifierTypeList;
    @XmlElement(name = "V4_StateID")
    protected List<String> v4StateID;
    @XmlElement(name = "V4_Function")
    protected List<V4Function> v4Function;
    @XmlElement(name = "UserEntry")
    protected Boolean userEntry;
    @XmlElement(name = "Hidden")
    protected Boolean hidden;

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the subType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubType() {
        return subType;
    }

    /**
     * Sets the value of the subType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubType(String value) {
        this.subType = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the initialValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialValue() {
        return initialValue;
    }

    /**
     * Sets the value of the initialValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialValue(String value) {
        this.initialValue = value;
    }

    /**
     * Gets the value of the stateID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateID() {
        return stateID;
    }

    /**
     * Sets the value of the stateID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateID(String value) {
        this.stateID = value;
    }

    /**
     * Gets the value of the v4ModifierTypeList property.
     * 
     * @return
     *     possible object is
     *     {@link V4ModifierTypeList }
     *     
     */
    public V4ModifierTypeList getV4ModifierTypeList() {
        return v4ModifierTypeList;
    }

    /**
     * Sets the value of the v4ModifierTypeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link V4ModifierTypeList }
     *     
     */
    public void setV4ModifierTypeList(V4ModifierTypeList value) {
        this.v4ModifierTypeList = value;
    }

    /**
     * Gets the value of the v4StateID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the v4StateID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getV4StateID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getV4StateID() {
        if (v4StateID == null) {
            v4StateID = new ArrayList<String>();
        }
        return this.v4StateID;
    }

    /**
     * Gets the value of the v4Function property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the v4Function property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getV4Function().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link V4Function }
     * 
     * 
     */
    public List<V4Function> getV4Function() {
        if (v4Function == null) {
            v4Function = new ArrayList<V4Function>();
        }
        return this.v4Function;
    }

    /**
     * Gets the value of the userEntry property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUserEntry() {
        return userEntry;
    }

    /**
     * Sets the value of the userEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUserEntry(Boolean value) {
        this.userEntry = value;
    }

    /**
     * Gets the value of the hidden property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHidden() {
        return hidden;
    }

    /**
     * Sets the value of the hidden property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHidden(Boolean value) {
        this.hidden = value;
    }

}
