//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.27 at 09:58:38 PM GMT 
//


package rpg.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import rpg.jaxb.CharacterRecord.CombatData;
import rpg.jaxb.CharacterRecord.CombatData.ArmorClass;
import rpg.jaxb.CharacterRecord.CombatData.AttackBonus;
import rpg.jaxb.CharacterRecord.CombatData.Initiative;
import rpg.jaxb.CharacterRecord.CombatData.Initiative.MiscModifier;
import rpg.jaxb.CharacterRecord.Description;
import rpg.jaxb.CharacterRecord.Inventory;
import rpg.jaxb.CharacterRecord.Inventory.EquippedItem;
import rpg.jaxb.CharacterRecord.Inventory.UnequippedItem;
import rpg.jaxb.CharacterRecord.Level;
import rpg.jaxb.CharacterRecord.Level.FeatsSelectedThisLevel;
import rpg.jaxb.CharacterRecord.SavingThrow;
import rpg.jaxb.CharacterRecord.SelectedFeats;


/**
 * Contains all data of one entity
 * 
 * <p>Java class for CharacterRecord element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="CharacterRecord">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="Description">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="CharacterName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="PlayerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="CharacterClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element ref="{rgb.jaxb.character}Race"/>
 *                     &lt;element name="Alignment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="Deity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                     &lt;element name="TotalLevel" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="Age" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="Height" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="Weight" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="EyeColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="HairColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="Ability" maxOccurs="6" minOccurs="6">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="Score" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="TmpScore" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="SavingThrow" maxOccurs="3" minOccurs="3">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="AbilityDependency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="Total" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="BaseSave" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="AbilityModifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="MagicModifier" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
 *                     &lt;element name="MiscModifier" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
 *                     &lt;element name="TempModifier" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="CombatData">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="AttackBonus" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="TotalAttackBonus" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                               &lt;element name="BaseAttackBonus" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                               &lt;element name="AbilityModifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                               &lt;element name="SizeModifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                               &lt;element name="MiscModifier" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
 *                               &lt;element name="TempModifier" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;/sequence>
 *                             &lt;attribute name="AbilityDependency" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Wounds" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="ArmorClass">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="Total" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                               &lt;element name="ArmorBonus" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                               &lt;element name="ShieldBonus" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                               &lt;element name="DexModifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                               &lt;element name="SizeModifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                               &lt;element name="MiscModifier" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
 *                               &lt;element name="BaseScore" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Initiative">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="Total" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                               &lt;element name="AbilityModifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                               &lt;element name="MiscModifier" maxOccurs="unbounded" minOccurs="0">
 *                                 &lt;complexType>
 *                                   &lt;simpleContent>
 *                                     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
 *                                       &lt;attribute name="Modifier" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                       &lt;attribute name="Source" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;/extension>
 *                                   &lt;/simpleContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                             &lt;attribute name="AbilityDependency" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Speed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="Inventory">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="EquippedItem" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attribute name="BodyPartName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;attribute name="ItemName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="UnequippedItem" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attribute name="ItemName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="SkillListLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="Level" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="ClassName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="HPThisLevel" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="Ability" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="AbilityName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="PointsIncreasedThisLevel" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="FeatsSelectedThisLevel" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="FeatName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="Special" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element ref="{rgb.jaxb.character}SkillList"/>
 *           &lt;element name="SelectedFeats" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="FeatName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "ability",
    "savingThrow",
    "combatData",
    "inventory",
    "skillListLocation",
    "level",
    "skillList",
    "selectedFeats"
})
@XmlRootElement(name = "CharacterRecord")
public class CharacterRecord {

    @XmlElement(name = "Description", namespace = "rgb.jaxb.character", required = true)
    protected Description description;
    @XmlElement(name = "Ability", namespace = "rgb.jaxb.character", required = true)
    protected List<rpg.jaxb.CharacterRecord.Ability> ability;
    @XmlElement(name = "SavingThrow", namespace = "rgb.jaxb.character", required = true)
    protected List<SavingThrow> savingThrow;
    @XmlElement(name = "CombatData", namespace = "rgb.jaxb.character", required = true)
    protected CombatData combatData;
    @XmlElement(name = "Inventory", namespace = "rgb.jaxb.character", required = true)
    protected Inventory inventory;
    @XmlElement(name = "SkillListLocation", namespace = "rgb.jaxb.character", required = true)
    protected String skillListLocation;
    @XmlElement(name = "Level", namespace = "rgb.jaxb.character", required = true)
    protected List<Level> level;
    @XmlElement(name = "SkillList", namespace = "rgb.jaxb.character", required = true)
    protected SkillList skillList;
    @XmlElement(name = "SelectedFeats", namespace = "rgb.jaxb.character")
    protected SelectedFeats selectedFeats;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescription(Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the ability property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ability property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAbility().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link rpg.jaxb.CharacterRecord.Ability }
     * 
     * 
     */
    public List<rpg.jaxb.CharacterRecord.Ability> getAbility() {
        if (ability == null) {
            ability = new ArrayList<rpg.jaxb.CharacterRecord.Ability>();
        }
        return this.ability;
    }

    /**
     * Gets the value of the savingThrow property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the savingThrow property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSavingThrow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SavingThrow }
     * 
     * 
     */
    public List<SavingThrow> getSavingThrow() {
        if (savingThrow == null) {
            savingThrow = new ArrayList<SavingThrow>();
        }
        return this.savingThrow;
    }

    /**
     * Gets the value of the combatData property.
     * 
     * @return
     *     possible object is
     *     {@link CombatData }
     *     
     */
    public CombatData getCombatData() {
        return combatData;
    }

    /**
     * Sets the value of the combatData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CombatData }
     *     
     */
    public void setCombatData(CombatData value) {
        this.combatData = value;
    }

    /**
     * Gets the value of the inventory property.
     * 
     * @return
     *     possible object is
     *     {@link Inventory }
     *     
     */
    public Inventory getInventory() {
        return inventory;
    }

    /**
     * Sets the value of the inventory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Inventory }
     *     
     */
    public void setInventory(Inventory value) {
        this.inventory = value;
    }

    /**
     * Gets the value of the skillListLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkillListLocation() {
        return skillListLocation;
    }

    /**
     * Sets the value of the skillListLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkillListLocation(String value) {
        this.skillListLocation = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the level property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLevel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Level }
     * 
     * 
     */
    public List<Level> getLevel() {
        if (level == null) {
            level = new ArrayList<Level>();
        }
        return this.level;
    }

    /**
     * Gets the value of the skillList property.
     * 
     * @return
     *     possible object is
     *     {@link SkillList }
     *     
     */
    public SkillList getSkillList() {
        return skillList;
    }

    /**
     * Sets the value of the skillList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkillList }
     *     
     */
    public void setSkillList(SkillList value) {
        this.skillList = value;
    }

    /**
     * Gets the value of the selectedFeats property.
     * 
     * @return
     *     possible object is
     *     {@link SelectedFeats }
     *     
     */
    public SelectedFeats getSelectedFeats() {
        return selectedFeats;
    }

    /**
     * Sets the value of the selectedFeats property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectedFeats }
     *     
     */
    public void setSelectedFeats(SelectedFeats value) {
        this.selectedFeats = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Score" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="TmpScore" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "score",
        "tmpScore"
    })
    public static class Ability {

        @XmlElement(name = "Name", namespace = "rgb.jaxb.character", required = true)
        protected String name;
        @XmlElement(name = "Score", namespace = "rgb.jaxb.character")
        protected int score;
        @XmlElement(name = "TmpScore", namespace = "rgb.jaxb.character")
        protected Integer tmpScore;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the score property.
         * 
         */
        public int getScore() {
            return score;
        }

        /**
         * Sets the value of the score property.
         * 
         */
        public void setScore(int value) {
            this.score = value;
        }

        /**
         * Gets the value of the tmpScore property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getTmpScore() {
            return tmpScore;
        }

        /**
         * Sets the value of the tmpScore property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setTmpScore(Integer value) {
            this.tmpScore = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AttackBonus" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TotalAttackBonus" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="BaseAttackBonus" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="AbilityModifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="SizeModifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="MiscModifier" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="TempModifier" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="AbilityDependency" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Wounds" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="ArmorClass">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Total" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ArmorBonus" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="ShieldBonus" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="DexModifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="SizeModifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="MiscModifier" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="BaseScore" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Initiative">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Total" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="AbilityModifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="MiscModifier" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
     *                           &lt;attribute name="Modifier" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="Source" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="AbilityDependency" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Speed" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attackBonus",
        "wounds",
        "armorClass",
        "initiative",
        "speed"
    })
    public static class CombatData {

        @XmlElement(name = "AttackBonus", namespace = "rgb.jaxb.character", required = true)
        protected List<AttackBonus> attackBonus;
        @XmlElement(name = "Wounds", namespace = "rgb.jaxb.character")
        protected int wounds;
        @XmlElement(name = "ArmorClass", namespace = "rgb.jaxb.character", required = true)
        protected ArmorClass armorClass;
        @XmlElement(name = "Initiative", namespace = "rgb.jaxb.character", required = true)
        protected Initiative initiative;
        @XmlElement(name = "Speed", namespace = "rgb.jaxb.character")
        protected int speed;

        /**
         * Gets the value of the attackBonus property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attackBonus property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttackBonus().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AttackBonus }
         * 
         * 
         */
        public List<AttackBonus> getAttackBonus() {
            if (attackBonus == null) {
                attackBonus = new ArrayList<AttackBonus>();
            }
            return this.attackBonus;
        }

        /**
         * Gets the value of the wounds property.
         * 
         */
        public int getWounds() {
            return wounds;
        }

        /**
         * Sets the value of the wounds property.
         * 
         */
        public void setWounds(int value) {
            this.wounds = value;
        }

        /**
         * Gets the value of the armorClass property.
         * 
         * @return
         *     possible object is
         *     {@link ArmorClass }
         *     
         */
        public ArmorClass getArmorClass() {
            return armorClass;
        }

        /**
         * Sets the value of the armorClass property.
         * 
         * @param value
         *     allowed object is
         *     {@link ArmorClass }
         *     
         */
        public void setArmorClass(ArmorClass value) {
            this.armorClass = value;
        }

        /**
         * Gets the value of the initiative property.
         * 
         * @return
         *     possible object is
         *     {@link Initiative }
         *     
         */
        public Initiative getInitiative() {
            return initiative;
        }

        /**
         * Sets the value of the initiative property.
         * 
         * @param value
         *     allowed object is
         *     {@link Initiative }
         *     
         */
        public void setInitiative(Initiative value) {
            this.initiative = value;
        }

        /**
         * Gets the value of the speed property.
         * 
         */
        public int getSpeed() {
            return speed;
        }

        /**
         * Sets the value of the speed property.
         * 
         */
        public void setSpeed(int value) {
            this.speed = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Total" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ArmorBonus" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="ShieldBonus" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="DexModifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="SizeModifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="MiscModifier" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="BaseScore" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "total",
            "armorBonus",
            "shieldBonus",
            "dexModifier",
            "sizeModifier",
            "miscModifier",
            "baseScore"
        })
        public static class ArmorClass {

            @XmlElement(name = "Total", namespace = "rgb.jaxb.character")
            protected int total;
            @XmlElement(name = "ArmorBonus", namespace = "rgb.jaxb.character")
            protected Integer armorBonus;
            @XmlElement(name = "ShieldBonus", namespace = "rgb.jaxb.character")
            protected Integer shieldBonus;
            @XmlElement(name = "DexModifier", namespace = "rgb.jaxb.character")
            protected int dexModifier;
            @XmlElement(name = "SizeModifier", namespace = "rgb.jaxb.character")
            protected int sizeModifier;
            @XmlElement(name = "MiscModifier", namespace = "rgb.jaxb.character", type = Integer.class)
            protected List<Integer> miscModifier;
            @XmlElement(name = "BaseScore", namespace = "rgb.jaxb.character")
            protected int baseScore;

            /**
             * Gets the value of the total property.
             * 
             */
            public int getTotal() {
                return total;
            }

            /**
             * Sets the value of the total property.
             * 
             */
            public void setTotal(int value) {
                this.total = value;
            }

            /**
             * Gets the value of the armorBonus property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getArmorBonus() {
                return armorBonus;
            }

            /**
             * Sets the value of the armorBonus property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setArmorBonus(Integer value) {
                this.armorBonus = value;
            }

            /**
             * Gets the value of the shieldBonus property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getShieldBonus() {
                return shieldBonus;
            }

            /**
             * Sets the value of the shieldBonus property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setShieldBonus(Integer value) {
                this.shieldBonus = value;
            }

            /**
             * Gets the value of the dexModifier property.
             * 
             */
            public int getDexModifier() {
                return dexModifier;
            }

            /**
             * Sets the value of the dexModifier property.
             * 
             */
            public void setDexModifier(int value) {
                this.dexModifier = value;
            }

            /**
             * Gets the value of the sizeModifier property.
             * 
             */
            public int getSizeModifier() {
                return sizeModifier;
            }

            /**
             * Sets the value of the sizeModifier property.
             * 
             */
            public void setSizeModifier(int value) {
                this.sizeModifier = value;
            }

            /**
             * Gets the value of the miscModifier property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the miscModifier property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getMiscModifier().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Integer }
             * 
             * 
             */
            public List<Integer> getMiscModifier() {
                if (miscModifier == null) {
                    miscModifier = new ArrayList<Integer>();
                }
                return this.miscModifier;
            }

            /**
             * Gets the value of the baseScore property.
             * 
             */
            public int getBaseScore() {
                return baseScore;
            }

            /**
             * Sets the value of the baseScore property.
             * 
             */
            public void setBaseScore(int value) {
                this.baseScore = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TotalAttackBonus" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="BaseAttackBonus" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="AbilityModifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="SizeModifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="MiscModifier" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="TempModifier" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="AbilityDependency" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "totalAttackBonus",
            "baseAttackBonus",
            "abilityModifier",
            "sizeModifier",
            "miscModifier",
            "tempModifier"
        })
        public static class AttackBonus {

            @XmlElement(name = "TotalAttackBonus", namespace = "rgb.jaxb.character")
            protected int totalAttackBonus;
            @XmlElement(name = "BaseAttackBonus", namespace = "rgb.jaxb.character")
            protected int baseAttackBonus;
            @XmlElement(name = "AbilityModifier", namespace = "rgb.jaxb.character")
            protected int abilityModifier;
            @XmlElement(name = "SizeModifier", namespace = "rgb.jaxb.character")
            protected int sizeModifier;
            @XmlElement(name = "MiscModifier", namespace = "rgb.jaxb.character", type = Integer.class)
            protected List<Integer> miscModifier;
            @XmlElement(name = "TempModifier", namespace = "rgb.jaxb.character", type = Integer.class)
            protected List<Integer> tempModifier;
            @XmlAttribute(name = "AbilityDependency", required = true)
            protected String abilityDependency;

            /**
             * Gets the value of the totalAttackBonus property.
             * 
             */
            public int getTotalAttackBonus() {
                return totalAttackBonus;
            }

            /**
             * Sets the value of the totalAttackBonus property.
             * 
             */
            public void setTotalAttackBonus(int value) {
                this.totalAttackBonus = value;
            }

            /**
             * Gets the value of the baseAttackBonus property.
             * 
             */
            public int getBaseAttackBonus() {
                return baseAttackBonus;
            }

            /**
             * Sets the value of the baseAttackBonus property.
             * 
             */
            public void setBaseAttackBonus(int value) {
                this.baseAttackBonus = value;
            }

            /**
             * Gets the value of the abilityModifier property.
             * 
             */
            public int getAbilityModifier() {
                return abilityModifier;
            }

            /**
             * Sets the value of the abilityModifier property.
             * 
             */
            public void setAbilityModifier(int value) {
                this.abilityModifier = value;
            }

            /**
             * Gets the value of the sizeModifier property.
             * 
             */
            public int getSizeModifier() {
                return sizeModifier;
            }

            /**
             * Sets the value of the sizeModifier property.
             * 
             */
            public void setSizeModifier(int value) {
                this.sizeModifier = value;
            }

            /**
             * Gets the value of the miscModifier property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the miscModifier property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getMiscModifier().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Integer }
             * 
             * 
             */
            public List<Integer> getMiscModifier() {
                if (miscModifier == null) {
                    miscModifier = new ArrayList<Integer>();
                }
                return this.miscModifier;
            }

            /**
             * Gets the value of the tempModifier property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the tempModifier property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTempModifier().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Integer }
             * 
             * 
             */
            public List<Integer> getTempModifier() {
                if (tempModifier == null) {
                    tempModifier = new ArrayList<Integer>();
                }
                return this.tempModifier;
            }

            /**
             * Gets the value of the abilityDependency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAbilityDependency() {
                return abilityDependency;
            }

            /**
             * Sets the value of the abilityDependency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAbilityDependency(String value) {
                this.abilityDependency = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Total" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="AbilityModifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="MiscModifier" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
         *                 &lt;attribute name="Modifier" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="Source" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="AbilityDependency" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "total",
            "abilityModifier",
            "miscModifier"
        })
        public static class Initiative {

            @XmlElement(name = "Total", namespace = "rgb.jaxb.character")
            protected int total;
            @XmlElement(name = "AbilityModifier", namespace = "rgb.jaxb.character")
            protected int abilityModifier;
            @XmlElement(name = "MiscModifier", namespace = "rgb.jaxb.character", required = true)
            protected List<MiscModifier> miscModifier;
            @XmlAttribute(name = "AbilityDependency", required = true)
            protected String abilityDependency;

            /**
             * Gets the value of the total property.
             * 
             */
            public int getTotal() {
                return total;
            }

            /**
             * Sets the value of the total property.
             * 
             */
            public void setTotal(int value) {
                this.total = value;
            }

            /**
             * Gets the value of the abilityModifier property.
             * 
             */
            public int getAbilityModifier() {
                return abilityModifier;
            }

            /**
             * Sets the value of the abilityModifier property.
             * 
             */
            public void setAbilityModifier(int value) {
                this.abilityModifier = value;
            }

            /**
             * Gets the value of the miscModifier property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the miscModifier property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getMiscModifier().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link MiscModifier }
             * 
             * 
             */
            public List<MiscModifier> getMiscModifier() {
                if (miscModifier == null) {
                    miscModifier = new ArrayList<MiscModifier>();
                }
                return this.miscModifier;
            }

            /**
             * Gets the value of the abilityDependency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAbilityDependency() {
                return abilityDependency;
            }

            /**
             * Sets the value of the abilityDependency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAbilityDependency(String value) {
                this.abilityDependency = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
             *       &lt;attribute name="Modifier" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="Source" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class MiscModifier {

                @XmlValue
                protected int value;
                @XmlAttribute(name = "Modifier", required = true)
                protected int modifier;
                @XmlAttribute(name = "Source", required = true)
                protected String source;

                /**
                 * Gets the value of the value property.
                 * 
                 */
                public int getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 */
                public void setValue(int value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the modifier property.
                 * 
                 */
                public int getModifier() {
                    return modifier;
                }

                /**
                 * Sets the value of the modifier property.
                 * 
                 */
                public void setModifier(int value) {
                    this.modifier = value;
                }

                /**
                 * Gets the value of the source property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSource() {
                    return source;
                }

                /**
                 * Sets the value of the source property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSource(String value) {
                    this.source = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CharacterName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PlayerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CharacterClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element ref="{rgb.jaxb.character}Race"/>
     *         &lt;element name="Alignment" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Deity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="TotalLevel" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Age" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Height" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Weight" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="EyeColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HairColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "characterName",
        "playerName",
        "characterClass",
        "race",
        "alignment",
        "deity",
        "totalLevel",
        "age",
        "gender",
        "height",
        "weight",
        "eyeColor",
        "hairColor"
    })
    public static class Description {

        @XmlElement(name = "CharacterName", namespace = "rgb.jaxb.character", required = true)
        protected String characterName;
        @XmlElement(name = "PlayerName", namespace = "rgb.jaxb.character", required = true)
        protected String playerName;
        @XmlElement(name = "CharacterClass", namespace = "rgb.jaxb.character", required = true)
        protected String characterClass;
        @XmlElement(name = "Race", namespace = "rgb.jaxb.character", required = true)
        protected Race race;
        @XmlElement(name = "Alignment", namespace = "rgb.jaxb.character", required = true)
        protected String alignment;
        @XmlElementRef(name = "Deity", namespace = "rgb.jaxb.character", type = JAXBElement.class)
        protected JAXBElement<String> deity;
        @XmlElement(name = "TotalLevel", namespace = "rgb.jaxb.character", defaultValue = "1")
        protected int totalLevel;
        @XmlElement(name = "Age", namespace = "rgb.jaxb.character", required = true)
        protected String age;
        @XmlElement(name = "Gender", namespace = "rgb.jaxb.character", required = true, defaultValue = "Male")
        protected String gender;
        @XmlElement(name = "Height", namespace = "rgb.jaxb.character", required = true)
        protected String height;
        @XmlElement(name = "Weight", namespace = "rgb.jaxb.character", required = true)
        protected String weight;
        @XmlElement(name = "EyeColor", namespace = "rgb.jaxb.character", required = true)
        protected String eyeColor;
        @XmlElement(name = "HairColor", namespace = "rgb.jaxb.character", required = true)
        protected String hairColor;

        /**
         * Gets the value of the characterName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCharacterName() {
            return characterName;
        }

        /**
         * Sets the value of the characterName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCharacterName(String value) {
            this.characterName = value;
        }

        /**
         * Gets the value of the playerName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlayerName() {
            return playerName;
        }

        /**
         * Sets the value of the playerName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlayerName(String value) {
            this.playerName = value;
        }

        /**
         * Gets the value of the characterClass property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCharacterClass() {
            return characterClass;
        }

        /**
         * Sets the value of the characterClass property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCharacterClass(String value) {
            this.characterClass = value;
        }

        /**
         * Gets the value of the race property.
         * 
         * @return
         *     possible object is
         *     {@link Race }
         *     
         */
        public Race getRace() {
            return race;
        }

        /**
         * Sets the value of the race property.
         * 
         * @param value
         *     allowed object is
         *     {@link Race }
         *     
         */
        public void setRace(Race value) {
            this.race = value;
        }

        /**
         * Gets the value of the alignment property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAlignment() {
            return alignment;
        }

        /**
         * Sets the value of the alignment property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAlignment(String value) {
            this.alignment = value;
        }

        /**
         * Gets the value of the deity property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public JAXBElement<String> getDeity() {
            return deity;
        }

        /**
         * Sets the value of the deity property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setDeity(JAXBElement<String> value) {
            this.deity = ((JAXBElement<String> ) value);
        }

        /**
         * Gets the value of the totalLevel property.
         * 
         */
        public int getTotalLevel() {
            return totalLevel;
        }

        /**
         * Sets the value of the totalLevel property.
         * 
         */
        public void setTotalLevel(int value) {
            this.totalLevel = value;
        }

        /**
         * Gets the value of the age property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAge() {
            return age;
        }

        /**
         * Sets the value of the age property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAge(String value) {
            this.age = value;
        }

        /**
         * Gets the value of the gender property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGender() {
            return gender;
        }

        /**
         * Sets the value of the gender property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGender(String value) {
            this.gender = value;
        }

        /**
         * Gets the value of the height property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHeight() {
            return height;
        }

        /**
         * Sets the value of the height property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHeight(String value) {
            this.height = value;
        }

        /**
         * Gets the value of the weight property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWeight() {
            return weight;
        }

        /**
         * Sets the value of the weight property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWeight(String value) {
            this.weight = value;
        }

        /**
         * Gets the value of the eyeColor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEyeColor() {
            return eyeColor;
        }

        /**
         * Sets the value of the eyeColor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEyeColor(String value) {
            this.eyeColor = value;
        }

        /**
         * Gets the value of the hairColor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHairColor() {
            return hairColor;
        }

        /**
         * Sets the value of the hairColor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHairColor(String value) {
            this.hairColor = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="EquippedItem" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="BodyPartName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="ItemName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="UnequippedItem" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="ItemName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "equippedItem",
        "unequippedItem"
    })
    public static class Inventory {

        @XmlElement(name = "EquippedItem", namespace = "rgb.jaxb.character", required = true)
        protected List<EquippedItem> equippedItem;
        @XmlElement(name = "UnequippedItem", namespace = "rgb.jaxb.character", required = true)
        protected List<UnequippedItem> unequippedItem;

        /**
         * Gets the value of the equippedItem property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the equippedItem property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEquippedItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EquippedItem }
         * 
         * 
         */
        public List<EquippedItem> getEquippedItem() {
            if (equippedItem == null) {
                equippedItem = new ArrayList<EquippedItem>();
            }
            return this.equippedItem;
        }

        /**
         * Gets the value of the unequippedItem property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the unequippedItem property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUnequippedItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UnequippedItem }
         * 
         * 
         */
        public List<UnequippedItem> getUnequippedItem() {
            if (unequippedItem == null) {
                unequippedItem = new ArrayList<UnequippedItem>();
            }
            return this.unequippedItem;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="BodyPartName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="ItemName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class EquippedItem {

            @XmlAttribute(name = "BodyPartName", required = true)
            protected String bodyPartName;
            @XmlAttribute(name = "ItemName", required = true)
            protected String itemName;

            /**
             * Gets the value of the bodyPartName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBodyPartName() {
                return bodyPartName;
            }

            /**
             * Sets the value of the bodyPartName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBodyPartName(String value) {
                this.bodyPartName = value;
            }

            /**
             * Gets the value of the itemName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getItemName() {
                return itemName;
            }

            /**
             * Sets the value of the itemName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setItemName(String value) {
                this.itemName = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="ItemName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class UnequippedItem {

            @XmlAttribute(name = "ItemName", required = true)
            protected String itemName;

            /**
             * Gets the value of the itemName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getItemName() {
                return itemName;
            }

            /**
             * Sets the value of the itemName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setItemName(String value) {
                this.itemName = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ClassName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HPThisLevel" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Ability" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="AbilityName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PointsIncreasedThisLevel" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="FeatsSelectedThisLevel" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="FeatName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Special" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "className",
        "hpThisLevel",
        "ability",
        "featsSelectedThisLevel"
    })
    public static class Level {

        @XmlElement(name = "ClassName", namespace = "rgb.jaxb.character", required = true)
        protected String className;
        @XmlElement(name = "HPThisLevel", namespace = "rgb.jaxb.character")
        protected int hpThisLevel;
        @XmlElement(name = "Ability", namespace = "rgb.jaxb.character", required = true)
        protected List<rpg.jaxb.CharacterRecord.Level.Ability> ability;
        @XmlElement(name = "FeatsSelectedThisLevel", namespace = "rgb.jaxb.character", required = true)
        protected List<FeatsSelectedThisLevel> featsSelectedThisLevel;

        /**
         * Gets the value of the className property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClassName() {
            return className;
        }

        /**
         * Sets the value of the className property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClassName(String value) {
            this.className = value;
        }

        /**
         * Gets the value of the hpThisLevel property.
         * 
         */
        public int getHPThisLevel() {
            return hpThisLevel;
        }

        /**
         * Sets the value of the hpThisLevel property.
         * 
         */
        public void setHPThisLevel(int value) {
            this.hpThisLevel = value;
        }

        /**
         * Gets the value of the ability property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ability property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAbility().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link rpg.jaxb.CharacterRecord.Level.Ability }
         * 
         * 
         */
        public List<rpg.jaxb.CharacterRecord.Level.Ability> getAbility() {
            if (ability == null) {
                ability = new ArrayList<rpg.jaxb.CharacterRecord.Level.Ability>();
            }
            return this.ability;
        }

        /**
         * Gets the value of the featsSelectedThisLevel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the featsSelectedThisLevel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFeatsSelectedThisLevel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FeatsSelectedThisLevel }
         * 
         * 
         */
        public List<FeatsSelectedThisLevel> getFeatsSelectedThisLevel() {
            if (featsSelectedThisLevel == null) {
                featsSelectedThisLevel = new ArrayList<FeatsSelectedThisLevel>();
            }
            return this.featsSelectedThisLevel;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="AbilityName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PointsIncreasedThisLevel" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "abilityName",
            "pointsIncreasedThisLevel"
        })
        public static class Ability {

            @XmlElement(name = "AbilityName", namespace = "rgb.jaxb.character", required = true)
            protected String abilityName;
            @XmlElement(name = "PointsIncreasedThisLevel", namespace = "rgb.jaxb.character")
            protected int pointsIncreasedThisLevel;

            /**
             * Gets the value of the abilityName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAbilityName() {
                return abilityName;
            }

            /**
             * Sets the value of the abilityName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAbilityName(String value) {
                this.abilityName = value;
            }

            /**
             * Gets the value of the pointsIncreasedThisLevel property.
             * 
             */
            public int getPointsIncreasedThisLevel() {
                return pointsIncreasedThisLevel;
            }

            /**
             * Sets the value of the pointsIncreasedThisLevel property.
             * 
             */
            public void setPointsIncreasedThisLevel(int value) {
                this.pointsIncreasedThisLevel = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="FeatName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Special" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "featName",
            "special"
        })
        public static class FeatsSelectedThisLevel {

            @XmlElement(name = "FeatName", namespace = "rgb.jaxb.character", required = true)
            protected String featName;
            @XmlElement(name = "Special", namespace = "rgb.jaxb.character")
            protected String special;

            /**
             * Gets the value of the featName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFeatName() {
                return featName;
            }

            /**
             * Sets the value of the featName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFeatName(String value) {
                this.featName = value;
            }

            /**
             * Gets the value of the special property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSpecial() {
                return special;
            }

            /**
             * Sets the value of the special property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSpecial(String value) {
                this.special = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AbilityDependency" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Total" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="BaseSave" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="AbilityModifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="MagicModifier" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="MiscModifier" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="TempModifier" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "abilityDependency",
        "total",
        "baseSave",
        "abilityModifier",
        "magicModifier",
        "miscModifier",
        "tempModifier"
    })
    public static class SavingThrow {

        @XmlElement(name = "Name", namespace = "rgb.jaxb.character", required = true)
        protected String name;
        @XmlElement(name = "AbilityDependency", namespace = "rgb.jaxb.character", required = true)
        protected String abilityDependency;
        @XmlElement(name = "Total", namespace = "rgb.jaxb.character")
        protected int total;
        @XmlElement(name = "BaseSave", namespace = "rgb.jaxb.character")
        protected int baseSave;
        @XmlElement(name = "AbilityModifier", namespace = "rgb.jaxb.character")
        protected int abilityModifier;
        @XmlElement(name = "MagicModifier", namespace = "rgb.jaxb.character", type = Integer.class)
        protected List<Integer> magicModifier;
        @XmlElement(name = "MiscModifier", namespace = "rgb.jaxb.character", type = Integer.class)
        protected List<Integer> miscModifier;
        @XmlElement(name = "TempModifier", namespace = "rgb.jaxb.character", type = Integer.class)
        protected List<Integer> tempModifier;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the abilityDependency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAbilityDependency() {
            return abilityDependency;
        }

        /**
         * Sets the value of the abilityDependency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAbilityDependency(String value) {
            this.abilityDependency = value;
        }

        /**
         * Gets the value of the total property.
         * 
         */
        public int getTotal() {
            return total;
        }

        /**
         * Sets the value of the total property.
         * 
         */
        public void setTotal(int value) {
            this.total = value;
        }

        /**
         * Gets the value of the baseSave property.
         * 
         */
        public int getBaseSave() {
            return baseSave;
        }

        /**
         * Sets the value of the baseSave property.
         * 
         */
        public void setBaseSave(int value) {
            this.baseSave = value;
        }

        /**
         * Gets the value of the abilityModifier property.
         * 
         */
        public int getAbilityModifier() {
            return abilityModifier;
        }

        /**
         * Sets the value of the abilityModifier property.
         * 
         */
        public void setAbilityModifier(int value) {
            this.abilityModifier = value;
        }

        /**
         * Gets the value of the magicModifier property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the magicModifier property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMagicModifier().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getMagicModifier() {
            if (magicModifier == null) {
                magicModifier = new ArrayList<Integer>();
            }
            return this.magicModifier;
        }

        /**
         * Gets the value of the miscModifier property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the miscModifier property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMiscModifier().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getMiscModifier() {
            if (miscModifier == null) {
                miscModifier = new ArrayList<Integer>();
            }
            return this.miscModifier;
        }

        /**
         * Gets the value of the tempModifier property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tempModifier property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTempModifier().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getTempModifier() {
            if (tempModifier == null) {
                tempModifier = new ArrayList<Integer>();
            }
            return this.tempModifier;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FeatName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "featName"
    })
    public static class SelectedFeats {

        @XmlElement(name = "FeatName", namespace = "rgb.jaxb.character", required = true)
        protected String featName;

        /**
         * Gets the value of the featName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFeatName() {
            return featName;
        }

        /**
         * Sets the value of the featName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFeatName(String value) {
            this.featName = value;
        }

    }

}
