//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.27 at 09:58:38 PM GMT 
//


package rpg.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import rpg.jaxb.ThemeList.Theme;
import rpg.jaxb.ThemeList.Theme.BarFillColor;
import rpg.jaxb.ThemeList.Theme.BasicBackgroundColor;
import rpg.jaxb.ThemeList.Theme.BasicButtonBorderColor;
import rpg.jaxb.ThemeList.Theme.BasicButtonHoverColor;
import rpg.jaxb.ThemeList.Theme.BasicMenuButtonHoverColor;
import rpg.jaxb.ThemeList.Theme.BattleLogMenuBackgroundColor;
import rpg.jaxb.ThemeList.Theme.CharacterPageBackgroundColor;
import rpg.jaxb.ThemeList.Theme.DeadCharacterColor;
import rpg.jaxb.ThemeList.Theme.FirstLevelBackgroundColor;
import rpg.jaxb.ThemeList.Theme.GridMenuBackgroundColor;
import rpg.jaxb.ThemeList.Theme.OnClickBackgroundColor;
import rpg.jaxb.ThemeList.Theme.OnClickBorderColor;
import rpg.jaxb.ThemeList.Theme.SecondLevelBackgroundColor;
import rpg.jaxb.ThemeList.Theme.TextBasicColor;
import rpg.jaxb.ThemeList.Theme.TextOnClickColor;


/**
 * List of GUI themes of what colors to use.
 * 
 * <p>Java class for ThemeList element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="ThemeList">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="Theme" maxOccurs="unbounded">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="BarFillColor">
 *                       &lt;complexType>
 *                         &lt;simpleContent>
 *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                             &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;/extension>
 *                         &lt;/simpleContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="BasicBackgroundColor">
 *                       &lt;complexType>
 *                         &lt;simpleContent>
 *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                             &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;/extension>
 *                         &lt;/simpleContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="BasicButtonBorderColor">
 *                       &lt;complexType>
 *                         &lt;simpleContent>
 *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                             &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;/extension>
 *                         &lt;/simpleContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="BasicButtonHoverColor">
 *                       &lt;complexType>
 *                         &lt;simpleContent>
 *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                             &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;/extension>
 *                         &lt;/simpleContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="BattleLogMenuBackgroundColor">
 *                       &lt;complexType>
 *                         &lt;simpleContent>
 *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                             &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;/extension>
 *                         &lt;/simpleContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="BasicMenuButtonHoverColor">
 *                       &lt;complexType>
 *                         &lt;simpleContent>
 *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                             &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;/extension>
 *                         &lt;/simpleContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="DeadCharacterColor">
 *                       &lt;complexType>
 *                         &lt;simpleContent>
 *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                             &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;/extension>
 *                         &lt;/simpleContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="FirstLevelBackgroundColor">
 *                       &lt;complexType>
 *                         &lt;simpleContent>
 *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                             &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;/extension>
 *                         &lt;/simpleContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="GridMenuBackgroundColor">
 *                       &lt;complexType>
 *                         &lt;simpleContent>
 *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                             &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;/extension>
 *                         &lt;/simpleContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="OnClickBackgroundColor">
 *                       &lt;complexType>
 *                         &lt;simpleContent>
 *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                             &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;/extension>
 *                         &lt;/simpleContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="OnClickBorderColor">
 *                       &lt;complexType>
 *                         &lt;simpleContent>
 *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                             &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;/extension>
 *                         &lt;/simpleContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="SecondLevelBackgroundColor">
 *                       &lt;complexType>
 *                         &lt;simpleContent>
 *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                             &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;/extension>
 *                         &lt;/simpleContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="TextBasicColor">
 *                       &lt;complexType>
 *                         &lt;simpleContent>
 *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                             &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;/extension>
 *                         &lt;/simpleContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="TextOnClickColor">
 *                       &lt;complexType>
 *                         &lt;simpleContent>
 *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                             &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;/extension>
 *                         &lt;/simpleContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="CharacterPageBackgroundColor">
 *                       &lt;complexType>
 *                         &lt;simpleContent>
 *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                             &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                             &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;/extension>
 *                         &lt;/simpleContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "theme"
})
@XmlRootElement(name = "ThemeList")
public class ThemeList {

    @XmlElement(name = "Theme", namespace = "rgb.jaxb.character", required = true)
    protected List<Theme> theme;

    /**
     * Gets the value of the theme property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the theme property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTheme().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Theme }
     * 
     * 
     */
    public List<Theme> getTheme() {
        if (theme == null) {
            theme = new ArrayList<Theme>();
        }
        return this.theme;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BarFillColor">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="BasicBackgroundColor">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="BasicButtonBorderColor">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="BasicButtonHoverColor">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="BattleLogMenuBackgroundColor">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="BasicMenuButtonHoverColor">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="DeadCharacterColor">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="FirstLevelBackgroundColor">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="GridMenuBackgroundColor">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="OnClickBackgroundColor">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="OnClickBorderColor">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="SecondLevelBackgroundColor">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="TextBasicColor">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="TextOnClickColor">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="CharacterPageBackgroundColor">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "barFillColor",
        "basicBackgroundColor",
        "basicButtonBorderColor",
        "basicButtonHoverColor",
        "battleLogMenuBackgroundColor",
        "basicMenuButtonHoverColor",
        "deadCharacterColor",
        "firstLevelBackgroundColor",
        "gridMenuBackgroundColor",
        "onClickBackgroundColor",
        "onClickBorderColor",
        "secondLevelBackgroundColor",
        "textBasicColor",
        "textOnClickColor",
        "characterPageBackgroundColor"
    })
    public static class Theme {

        @XmlElement(name = "Name", namespace = "rgb.jaxb.character", required = true)
        protected String name;
        @XmlElement(name = "BarFillColor", namespace = "rgb.jaxb.character", required = true)
        protected BarFillColor barFillColor;
        @XmlElement(name = "BasicBackgroundColor", namespace = "rgb.jaxb.character", required = true)
        protected BasicBackgroundColor basicBackgroundColor;
        @XmlElement(name = "BasicButtonBorderColor", namespace = "rgb.jaxb.character", required = true)
        protected BasicButtonBorderColor basicButtonBorderColor;
        @XmlElement(name = "BasicButtonHoverColor", namespace = "rgb.jaxb.character", required = true)
        protected BasicButtonHoverColor basicButtonHoverColor;
        @XmlElement(name = "BattleLogMenuBackgroundColor", namespace = "rgb.jaxb.character", required = true)
        protected BattleLogMenuBackgroundColor battleLogMenuBackgroundColor;
        @XmlElement(name = "BasicMenuButtonHoverColor", namespace = "rgb.jaxb.character", required = true)
        protected BasicMenuButtonHoverColor basicMenuButtonHoverColor;
        @XmlElement(name = "DeadCharacterColor", namespace = "rgb.jaxb.character", required = true)
        protected DeadCharacterColor deadCharacterColor;
        @XmlElement(name = "FirstLevelBackgroundColor", namespace = "rgb.jaxb.character", required = true)
        protected FirstLevelBackgroundColor firstLevelBackgroundColor;
        @XmlElement(name = "GridMenuBackgroundColor", namespace = "rgb.jaxb.character", required = true)
        protected GridMenuBackgroundColor gridMenuBackgroundColor;
        @XmlElement(name = "OnClickBackgroundColor", namespace = "rgb.jaxb.character", required = true)
        protected OnClickBackgroundColor onClickBackgroundColor;
        @XmlElement(name = "OnClickBorderColor", namespace = "rgb.jaxb.character", required = true)
        protected OnClickBorderColor onClickBorderColor;
        @XmlElement(name = "SecondLevelBackgroundColor", namespace = "rgb.jaxb.character", required = true)
        protected SecondLevelBackgroundColor secondLevelBackgroundColor;
        @XmlElement(name = "TextBasicColor", namespace = "rgb.jaxb.character", required = true)
        protected TextBasicColor textBasicColor;
        @XmlElement(name = "TextOnClickColor", namespace = "rgb.jaxb.character", required = true)
        protected TextOnClickColor textOnClickColor;
        @XmlElement(name = "CharacterPageBackgroundColor", namespace = "rgb.jaxb.character", required = true)
        protected CharacterPageBackgroundColor characterPageBackgroundColor;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the barFillColor property.
         * 
         * @return
         *     possible object is
         *     {@link BarFillColor }
         *     
         */
        public BarFillColor getBarFillColor() {
            return barFillColor;
        }

        /**
         * Sets the value of the barFillColor property.
         * 
         * @param value
         *     allowed object is
         *     {@link BarFillColor }
         *     
         */
        public void setBarFillColor(BarFillColor value) {
            this.barFillColor = value;
        }

        /**
         * Gets the value of the basicBackgroundColor property.
         * 
         * @return
         *     possible object is
         *     {@link BasicBackgroundColor }
         *     
         */
        public BasicBackgroundColor getBasicBackgroundColor() {
            return basicBackgroundColor;
        }

        /**
         * Sets the value of the basicBackgroundColor property.
         * 
         * @param value
         *     allowed object is
         *     {@link BasicBackgroundColor }
         *     
         */
        public void setBasicBackgroundColor(BasicBackgroundColor value) {
            this.basicBackgroundColor = value;
        }

        /**
         * Gets the value of the basicButtonBorderColor property.
         * 
         * @return
         *     possible object is
         *     {@link BasicButtonBorderColor }
         *     
         */
        public BasicButtonBorderColor getBasicButtonBorderColor() {
            return basicButtonBorderColor;
        }

        /**
         * Sets the value of the basicButtonBorderColor property.
         * 
         * @param value
         *     allowed object is
         *     {@link BasicButtonBorderColor }
         *     
         */
        public void setBasicButtonBorderColor(BasicButtonBorderColor value) {
            this.basicButtonBorderColor = value;
        }

        /**
         * Gets the value of the basicButtonHoverColor property.
         * 
         * @return
         *     possible object is
         *     {@link BasicButtonHoverColor }
         *     
         */
        public BasicButtonHoverColor getBasicButtonHoverColor() {
            return basicButtonHoverColor;
        }

        /**
         * Sets the value of the basicButtonHoverColor property.
         * 
         * @param value
         *     allowed object is
         *     {@link BasicButtonHoverColor }
         *     
         */
        public void setBasicButtonHoverColor(BasicButtonHoverColor value) {
            this.basicButtonHoverColor = value;
        }

        /**
         * Gets the value of the battleLogMenuBackgroundColor property.
         * 
         * @return
         *     possible object is
         *     {@link BattleLogMenuBackgroundColor }
         *     
         */
        public BattleLogMenuBackgroundColor getBattleLogMenuBackgroundColor() {
            return battleLogMenuBackgroundColor;
        }

        /**
         * Sets the value of the battleLogMenuBackgroundColor property.
         * 
         * @param value
         *     allowed object is
         *     {@link BattleLogMenuBackgroundColor }
         *     
         */
        public void setBattleLogMenuBackgroundColor(BattleLogMenuBackgroundColor value) {
            this.battleLogMenuBackgroundColor = value;
        }

        /**
         * Gets the value of the basicMenuButtonHoverColor property.
         * 
         * @return
         *     possible object is
         *     {@link BasicMenuButtonHoverColor }
         *     
         */
        public BasicMenuButtonHoverColor getBasicMenuButtonHoverColor() {
            return basicMenuButtonHoverColor;
        }

        /**
         * Sets the value of the basicMenuButtonHoverColor property.
         * 
         * @param value
         *     allowed object is
         *     {@link BasicMenuButtonHoverColor }
         *     
         */
        public void setBasicMenuButtonHoverColor(BasicMenuButtonHoverColor value) {
            this.basicMenuButtonHoverColor = value;
        }

        /**
         * Gets the value of the deadCharacterColor property.
         * 
         * @return
         *     possible object is
         *     {@link DeadCharacterColor }
         *     
         */
        public DeadCharacterColor getDeadCharacterColor() {
            return deadCharacterColor;
        }

        /**
         * Sets the value of the deadCharacterColor property.
         * 
         * @param value
         *     allowed object is
         *     {@link DeadCharacterColor }
         *     
         */
        public void setDeadCharacterColor(DeadCharacterColor value) {
            this.deadCharacterColor = value;
        }

        /**
         * Gets the value of the firstLevelBackgroundColor property.
         * 
         * @return
         *     possible object is
         *     {@link FirstLevelBackgroundColor }
         *     
         */
        public FirstLevelBackgroundColor getFirstLevelBackgroundColor() {
            return firstLevelBackgroundColor;
        }

        /**
         * Sets the value of the firstLevelBackgroundColor property.
         * 
         * @param value
         *     allowed object is
         *     {@link FirstLevelBackgroundColor }
         *     
         */
        public void setFirstLevelBackgroundColor(FirstLevelBackgroundColor value) {
            this.firstLevelBackgroundColor = value;
        }

        /**
         * Gets the value of the gridMenuBackgroundColor property.
         * 
         * @return
         *     possible object is
         *     {@link GridMenuBackgroundColor }
         *     
         */
        public GridMenuBackgroundColor getGridMenuBackgroundColor() {
            return gridMenuBackgroundColor;
        }

        /**
         * Sets the value of the gridMenuBackgroundColor property.
         * 
         * @param value
         *     allowed object is
         *     {@link GridMenuBackgroundColor }
         *     
         */
        public void setGridMenuBackgroundColor(GridMenuBackgroundColor value) {
            this.gridMenuBackgroundColor = value;
        }

        /**
         * Gets the value of the onClickBackgroundColor property.
         * 
         * @return
         *     possible object is
         *     {@link OnClickBackgroundColor }
         *     
         */
        public OnClickBackgroundColor getOnClickBackgroundColor() {
            return onClickBackgroundColor;
        }

        /**
         * Sets the value of the onClickBackgroundColor property.
         * 
         * @param value
         *     allowed object is
         *     {@link OnClickBackgroundColor }
         *     
         */
        public void setOnClickBackgroundColor(OnClickBackgroundColor value) {
            this.onClickBackgroundColor = value;
        }

        /**
         * Gets the value of the onClickBorderColor property.
         * 
         * @return
         *     possible object is
         *     {@link OnClickBorderColor }
         *     
         */
        public OnClickBorderColor getOnClickBorderColor() {
            return onClickBorderColor;
        }

        /**
         * Sets the value of the onClickBorderColor property.
         * 
         * @param value
         *     allowed object is
         *     {@link OnClickBorderColor }
         *     
         */
        public void setOnClickBorderColor(OnClickBorderColor value) {
            this.onClickBorderColor = value;
        }

        /**
         * Gets the value of the secondLevelBackgroundColor property.
         * 
         * @return
         *     possible object is
         *     {@link SecondLevelBackgroundColor }
         *     
         */
        public SecondLevelBackgroundColor getSecondLevelBackgroundColor() {
            return secondLevelBackgroundColor;
        }

        /**
         * Sets the value of the secondLevelBackgroundColor property.
         * 
         * @param value
         *     allowed object is
         *     {@link SecondLevelBackgroundColor }
         *     
         */
        public void setSecondLevelBackgroundColor(SecondLevelBackgroundColor value) {
            this.secondLevelBackgroundColor = value;
        }

        /**
         * Gets the value of the textBasicColor property.
         * 
         * @return
         *     possible object is
         *     {@link TextBasicColor }
         *     
         */
        public TextBasicColor getTextBasicColor() {
            return textBasicColor;
        }

        /**
         * Sets the value of the textBasicColor property.
         * 
         * @param value
         *     allowed object is
         *     {@link TextBasicColor }
         *     
         */
        public void setTextBasicColor(TextBasicColor value) {
            this.textBasicColor = value;
        }

        /**
         * Gets the value of the textOnClickColor property.
         * 
         * @return
         *     possible object is
         *     {@link TextOnClickColor }
         *     
         */
        public TextOnClickColor getTextOnClickColor() {
            return textOnClickColor;
        }

        /**
         * Sets the value of the textOnClickColor property.
         * 
         * @param value
         *     allowed object is
         *     {@link TextOnClickColor }
         *     
         */
        public void setTextOnClickColor(TextOnClickColor value) {
            this.textOnClickColor = value;
        }

        /**
         * Gets the value of the characterPageBackgroundColor property.
         * 
         * @return
         *     possible object is
         *     {@link CharacterPageBackgroundColor }
         *     
         */
        public CharacterPageBackgroundColor getCharacterPageBackgroundColor() {
            return characterPageBackgroundColor;
        }

        /**
         * Sets the value of the characterPageBackgroundColor property.
         * 
         * @param value
         *     allowed object is
         *     {@link CharacterPageBackgroundColor }
         *     
         */
        public void setCharacterPageBackgroundColor(CharacterPageBackgroundColor value) {
            this.characterPageBackgroundColor = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class BarFillColor {

            @XmlValue
            protected String value;
            @XmlAttribute
            protected Integer blue;
            @XmlAttribute
            protected Integer green;
            @XmlAttribute
            protected Integer red;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the blue property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBlue() {
                return blue;
            }

            /**
             * Sets the value of the blue property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBlue(Integer value) {
                this.blue = value;
            }

            /**
             * Gets the value of the green property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGreen() {
                return green;
            }

            /**
             * Sets the value of the green property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGreen(Integer value) {
                this.green = value;
            }

            /**
             * Gets the value of the red property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRed() {
                return red;
            }

            /**
             * Sets the value of the red property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRed(Integer value) {
                this.red = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class BasicBackgroundColor {

            @XmlValue
            protected String value;
            @XmlAttribute
            protected Integer blue;
            @XmlAttribute
            protected Integer green;
            @XmlAttribute
            protected Integer red;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the blue property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBlue() {
                return blue;
            }

            /**
             * Sets the value of the blue property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBlue(Integer value) {
                this.blue = value;
            }

            /**
             * Gets the value of the green property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGreen() {
                return green;
            }

            /**
             * Sets the value of the green property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGreen(Integer value) {
                this.green = value;
            }

            /**
             * Gets the value of the red property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRed() {
                return red;
            }

            /**
             * Sets the value of the red property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRed(Integer value) {
                this.red = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class BasicButtonBorderColor {

            @XmlValue
            protected String value;
            @XmlAttribute
            protected Integer blue;
            @XmlAttribute
            protected Integer green;
            @XmlAttribute
            protected Integer red;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the blue property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBlue() {
                return blue;
            }

            /**
             * Sets the value of the blue property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBlue(Integer value) {
                this.blue = value;
            }

            /**
             * Gets the value of the green property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGreen() {
                return green;
            }

            /**
             * Sets the value of the green property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGreen(Integer value) {
                this.green = value;
            }

            /**
             * Gets the value of the red property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRed() {
                return red;
            }

            /**
             * Sets the value of the red property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRed(Integer value) {
                this.red = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class BasicButtonHoverColor {

            @XmlValue
            protected String value;
            @XmlAttribute
            protected Integer blue;
            @XmlAttribute
            protected Integer green;
            @XmlAttribute
            protected Integer red;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the blue property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBlue() {
                return blue;
            }

            /**
             * Sets the value of the blue property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBlue(Integer value) {
                this.blue = value;
            }

            /**
             * Gets the value of the green property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGreen() {
                return green;
            }

            /**
             * Sets the value of the green property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGreen(Integer value) {
                this.green = value;
            }

            /**
             * Gets the value of the red property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRed() {
                return red;
            }

            /**
             * Sets the value of the red property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRed(Integer value) {
                this.red = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class BasicMenuButtonHoverColor {

            @XmlValue
            protected String value;
            @XmlAttribute
            protected Integer blue;
            @XmlAttribute
            protected Integer green;
            @XmlAttribute
            protected Integer red;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the blue property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBlue() {
                return blue;
            }

            /**
             * Sets the value of the blue property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBlue(Integer value) {
                this.blue = value;
            }

            /**
             * Gets the value of the green property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGreen() {
                return green;
            }

            /**
             * Sets the value of the green property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGreen(Integer value) {
                this.green = value;
            }

            /**
             * Gets the value of the red property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRed() {
                return red;
            }

            /**
             * Sets the value of the red property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRed(Integer value) {
                this.red = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class BattleLogMenuBackgroundColor {

            @XmlValue
            protected String value;
            @XmlAttribute
            protected Integer blue;
            @XmlAttribute
            protected Integer green;
            @XmlAttribute
            protected Integer red;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the blue property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBlue() {
                return blue;
            }

            /**
             * Sets the value of the blue property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBlue(Integer value) {
                this.blue = value;
            }

            /**
             * Gets the value of the green property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGreen() {
                return green;
            }

            /**
             * Sets the value of the green property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGreen(Integer value) {
                this.green = value;
            }

            /**
             * Gets the value of the red property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRed() {
                return red;
            }

            /**
             * Sets the value of the red property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRed(Integer value) {
                this.red = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class CharacterPageBackgroundColor {

            @XmlValue
            protected String value;
            @XmlAttribute
            protected Integer blue;
            @XmlAttribute
            protected Integer green;
            @XmlAttribute
            protected Integer red;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the blue property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBlue() {
                return blue;
            }

            /**
             * Sets the value of the blue property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBlue(Integer value) {
                this.blue = value;
            }

            /**
             * Gets the value of the green property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGreen() {
                return green;
            }

            /**
             * Sets the value of the green property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGreen(Integer value) {
                this.green = value;
            }

            /**
             * Gets the value of the red property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRed() {
                return red;
            }

            /**
             * Sets the value of the red property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRed(Integer value) {
                this.red = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class DeadCharacterColor {

            @XmlValue
            protected String value;
            @XmlAttribute
            protected Integer blue;
            @XmlAttribute
            protected Integer green;
            @XmlAttribute
            protected Integer red;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the blue property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBlue() {
                return blue;
            }

            /**
             * Sets the value of the blue property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBlue(Integer value) {
                this.blue = value;
            }

            /**
             * Gets the value of the green property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGreen() {
                return green;
            }

            /**
             * Sets the value of the green property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGreen(Integer value) {
                this.green = value;
            }

            /**
             * Gets the value of the red property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRed() {
                return red;
            }

            /**
             * Sets the value of the red property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRed(Integer value) {
                this.red = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class FirstLevelBackgroundColor {

            @XmlValue
            protected String value;
            @XmlAttribute
            protected Integer blue;
            @XmlAttribute
            protected Integer green;
            @XmlAttribute
            protected Integer red;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the blue property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBlue() {
                return blue;
            }

            /**
             * Sets the value of the blue property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBlue(Integer value) {
                this.blue = value;
            }

            /**
             * Gets the value of the green property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGreen() {
                return green;
            }

            /**
             * Sets the value of the green property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGreen(Integer value) {
                this.green = value;
            }

            /**
             * Gets the value of the red property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRed() {
                return red;
            }

            /**
             * Sets the value of the red property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRed(Integer value) {
                this.red = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class GridMenuBackgroundColor {

            @XmlValue
            protected String value;
            @XmlAttribute
            protected Integer blue;
            @XmlAttribute
            protected Integer green;
            @XmlAttribute
            protected Integer red;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the blue property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBlue() {
                return blue;
            }

            /**
             * Sets the value of the blue property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBlue(Integer value) {
                this.blue = value;
            }

            /**
             * Gets the value of the green property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGreen() {
                return green;
            }

            /**
             * Sets the value of the green property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGreen(Integer value) {
                this.green = value;
            }

            /**
             * Gets the value of the red property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRed() {
                return red;
            }

            /**
             * Sets the value of the red property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRed(Integer value) {
                this.red = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class OnClickBackgroundColor {

            @XmlValue
            protected String value;
            @XmlAttribute
            protected Integer blue;
            @XmlAttribute
            protected Integer green;
            @XmlAttribute
            protected Integer red;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the blue property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBlue() {
                return blue;
            }

            /**
             * Sets the value of the blue property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBlue(Integer value) {
                this.blue = value;
            }

            /**
             * Gets the value of the green property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGreen() {
                return green;
            }

            /**
             * Sets the value of the green property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGreen(Integer value) {
                this.green = value;
            }

            /**
             * Gets the value of the red property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRed() {
                return red;
            }

            /**
             * Sets the value of the red property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRed(Integer value) {
                this.red = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class OnClickBorderColor {

            @XmlValue
            protected String value;
            @XmlAttribute
            protected Integer blue;
            @XmlAttribute
            protected Integer green;
            @XmlAttribute
            protected Integer red;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the blue property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBlue() {
                return blue;
            }

            /**
             * Sets the value of the blue property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBlue(Integer value) {
                this.blue = value;
            }

            /**
             * Gets the value of the green property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGreen() {
                return green;
            }

            /**
             * Sets the value of the green property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGreen(Integer value) {
                this.green = value;
            }

            /**
             * Gets the value of the red property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRed() {
                return red;
            }

            /**
             * Sets the value of the red property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRed(Integer value) {
                this.red = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class SecondLevelBackgroundColor {

            @XmlValue
            protected String value;
            @XmlAttribute
            protected Integer blue;
            @XmlAttribute
            protected Integer green;
            @XmlAttribute
            protected Integer red;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the blue property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBlue() {
                return blue;
            }

            /**
             * Sets the value of the blue property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBlue(Integer value) {
                this.blue = value;
            }

            /**
             * Gets the value of the green property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGreen() {
                return green;
            }

            /**
             * Sets the value of the green property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGreen(Integer value) {
                this.green = value;
            }

            /**
             * Gets the value of the red property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRed() {
                return red;
            }

            /**
             * Sets the value of the red property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRed(Integer value) {
                this.red = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class TextBasicColor {

            @XmlValue
            protected String value;
            @XmlAttribute
            protected Integer blue;
            @XmlAttribute
            protected Integer green;
            @XmlAttribute
            protected Integer red;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the blue property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBlue() {
                return blue;
            }

            /**
             * Sets the value of the blue property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBlue(Integer value) {
                this.blue = value;
            }

            /**
             * Gets the value of the green property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGreen() {
                return green;
            }

            /**
             * Sets the value of the green property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGreen(Integer value) {
                this.green = value;
            }

            /**
             * Gets the value of the red property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRed() {
                return red;
            }

            /**
             * Sets the value of the red property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRed(Integer value) {
                this.red = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class TextOnClickColor {

            @XmlValue
            protected String value;
            @XmlAttribute
            protected Integer blue;
            @XmlAttribute
            protected Integer green;
            @XmlAttribute
            protected Integer red;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the blue property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBlue() {
                return blue;
            }

            /**
             * Sets the value of the blue property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBlue(Integer value) {
                this.blue = value;
            }

            /**
             * Gets the value of the green property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGreen() {
                return green;
            }

            /**
             * Sets the value of the green property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGreen(Integer value) {
                this.green = value;
            }

            /**
             * Gets the value of the red property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRed() {
                return red;
            }

            /**
             * Sets the value of the red property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRed(Integer value) {
                this.red = value;
            }

        }

    }

}
