//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.27 at 09:58:38 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "rgb.jaxb.character")
package rpg.jaxb;
