//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.27 at 09:58:38 PM GMT 
//


package rpg.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import rpg.jaxb.Weapon.Critical;
import rpg.jaxb.Weapon.Damage;
import rpg.jaxb.Weapon.Damage.Medium;
import rpg.jaxb.Weapon.Damage.Small;
import rpg.jaxb.Weapon.SpecialProperties;
import rpg.jaxb.Weapon.Weight;


/**
 * <p>Java class for Weapon element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="Weapon">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="Damage">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Small">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="LowerBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                               &lt;element name="UpperBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Medium">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="LowerBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                               &lt;element name="UpperBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="Critical">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="CriticalMultiplier" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="LowerBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="UpperBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="Weight">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Kilograms" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                     &lt;element name="Lbs" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="BattleForm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="SpecialProperties" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="PropertyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="PropertyType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                     &lt;element name="PropertyBonus" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="PropertyTarget" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="RangeIncrement" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "damage",
    "critical",
    "weight",
    "type",
    "battleForm",
    "category",
    "specialProperties",
    "rangeIncrement"
})
@XmlRootElement(name = "Weapon")
public class Weapon {

    @XmlElement(name = "Name", namespace = "rgb.jaxb.character", required = true)
    protected String name;
    @XmlElement(name = "Damage", namespace = "rgb.jaxb.character", required = true)
    protected Damage damage;
    @XmlElement(name = "Critical", namespace = "rgb.jaxb.character", required = true)
    protected Critical critical;
    @XmlElement(name = "Weight", namespace = "rgb.jaxb.character", required = true)
    protected Weight weight;
    @XmlElement(name = "Type", namespace = "rgb.jaxb.character", required = true)
    protected String type;
    @XmlElement(name = "BattleForm", namespace = "rgb.jaxb.character", required = true)
    protected String battleForm;
    @XmlElement(name = "Category", namespace = "rgb.jaxb.character", required = true)
    protected String category;
    @XmlElement(name = "SpecialProperties", namespace = "rgb.jaxb.character", required = true)
    protected List<SpecialProperties> specialProperties;
    @XmlElement(name = "RangeIncrement", namespace = "rgb.jaxb.character")
    protected Integer rangeIncrement;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the damage property.
     * 
     * @return
     *     possible object is
     *     {@link Damage }
     *     
     */
    public Damage getDamage() {
        return damage;
    }

    /**
     * Sets the value of the damage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Damage }
     *     
     */
    public void setDamage(Damage value) {
        this.damage = value;
    }

    /**
     * Gets the value of the critical property.
     * 
     * @return
     *     possible object is
     *     {@link Critical }
     *     
     */
    public Critical getCritical() {
        return critical;
    }

    /**
     * Sets the value of the critical property.
     * 
     * @param value
     *     allowed object is
     *     {@link Critical }
     *     
     */
    public void setCritical(Critical value) {
        this.critical = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link Weight }
     *     
     */
    public Weight getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Weight }
     *     
     */
    public void setWeight(Weight value) {
        this.weight = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the battleForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBattleForm() {
        return battleForm;
    }

    /**
     * Sets the value of the battleForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBattleForm(String value) {
        this.battleForm = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the specialProperties property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specialProperties property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecialProperties().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpecialProperties }
     * 
     * 
     */
    public List<SpecialProperties> getSpecialProperties() {
        if (specialProperties == null) {
            specialProperties = new ArrayList<SpecialProperties>();
        }
        return this.specialProperties;
    }

    /**
     * Gets the value of the rangeIncrement property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRangeIncrement() {
        return rangeIncrement;
    }

    /**
     * Sets the value of the rangeIncrement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRangeIncrement(Integer value) {
        this.rangeIncrement = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CriticalMultiplier" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="LowerBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="UpperBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "criticalMultiplier",
        "lowerBound",
        "upperBound"
    })
    public static class Critical {

        @XmlElement(name = "CriticalMultiplier", namespace = "rgb.jaxb.character")
        protected int criticalMultiplier;
        @XmlElement(name = "LowerBound", namespace = "rgb.jaxb.character")
        protected int lowerBound;
        @XmlElement(name = "UpperBound", namespace = "rgb.jaxb.character")
        protected int upperBound;

        /**
         * Gets the value of the criticalMultiplier property.
         * 
         */
        public int getCriticalMultiplier() {
            return criticalMultiplier;
        }

        /**
         * Sets the value of the criticalMultiplier property.
         * 
         */
        public void setCriticalMultiplier(int value) {
            this.criticalMultiplier = value;
        }

        /**
         * Gets the value of the lowerBound property.
         * 
         */
        public int getLowerBound() {
            return lowerBound;
        }

        /**
         * Sets the value of the lowerBound property.
         * 
         */
        public void setLowerBound(int value) {
            this.lowerBound = value;
        }

        /**
         * Gets the value of the upperBound property.
         * 
         */
        public int getUpperBound() {
            return upperBound;
        }

        /**
         * Sets the value of the upperBound property.
         * 
         */
        public void setUpperBound(int value) {
            this.upperBound = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Small">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="LowerBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="UpperBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Medium">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="LowerBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="UpperBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "small",
        "medium"
    })
    public static class Damage {

        @XmlElement(name = "Small", namespace = "rgb.jaxb.character", required = true)
        protected Small small;
        @XmlElement(name = "Medium", namespace = "rgb.jaxb.character", required = true)
        protected Medium medium;

        /**
         * Gets the value of the small property.
         * 
         * @return
         *     possible object is
         *     {@link Small }
         *     
         */
        public Small getSmall() {
            return small;
        }

        /**
         * Sets the value of the small property.
         * 
         * @param value
         *     allowed object is
         *     {@link Small }
         *     
         */
        public void setSmall(Small value) {
            this.small = value;
        }

        /**
         * Gets the value of the medium property.
         * 
         * @return
         *     possible object is
         *     {@link Medium }
         *     
         */
        public Medium getMedium() {
            return medium;
        }

        /**
         * Sets the value of the medium property.
         * 
         * @param value
         *     allowed object is
         *     {@link Medium }
         *     
         */
        public void setMedium(Medium value) {
            this.medium = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="LowerBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="UpperBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "lowerBound",
            "upperBound"
        })
        public static class Medium {

            @XmlElement(name = "LowerBound", namespace = "rgb.jaxb.character")
            protected int lowerBound;
            @XmlElement(name = "UpperBound", namespace = "rgb.jaxb.character")
            protected int upperBound;

            /**
             * Gets the value of the lowerBound property.
             * 
             */
            public int getLowerBound() {
                return lowerBound;
            }

            /**
             * Sets the value of the lowerBound property.
             * 
             */
            public void setLowerBound(int value) {
                this.lowerBound = value;
            }

            /**
             * Gets the value of the upperBound property.
             * 
             */
            public int getUpperBound() {
                return upperBound;
            }

            /**
             * Sets the value of the upperBound property.
             * 
             */
            public void setUpperBound(int value) {
                this.upperBound = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="LowerBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="UpperBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "lowerBound",
            "upperBound"
        })
        public static class Small {

            @XmlElement(name = "LowerBound", namespace = "rgb.jaxb.character")
            protected int lowerBound;
            @XmlElement(name = "UpperBound", namespace = "rgb.jaxb.character")
            protected int upperBound;

            /**
             * Gets the value of the lowerBound property.
             * 
             */
            public int getLowerBound() {
                return lowerBound;
            }

            /**
             * Sets the value of the lowerBound property.
             * 
             */
            public void setLowerBound(int value) {
                this.lowerBound = value;
            }

            /**
             * Gets the value of the upperBound property.
             * 
             */
            public int getUpperBound() {
                return upperBound;
            }

            /**
             * Sets the value of the upperBound property.
             * 
             */
            public void setUpperBound(int value) {
                this.upperBound = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PropertyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PropertyType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="PropertyBonus" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="PropertyTarget" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "propertyName",
        "propertyType",
        "propertyBonus",
        "propertyTarget"
    })
    public static class SpecialProperties {

        @XmlElement(name = "PropertyName", namespace = "rgb.jaxb.character", required = true)
        protected String propertyName;
        @XmlElement(name = "PropertyType", namespace = "rgb.jaxb.character", required = true)
        protected Object propertyType;
        @XmlElement(name = "PropertyBonus", namespace = "rgb.jaxb.character")
        protected int propertyBonus;
        @XmlElement(name = "PropertyTarget", namespace = "rgb.jaxb.character", required = true)
        protected String propertyTarget;

        /**
         * Gets the value of the propertyName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPropertyName() {
            return propertyName;
        }

        /**
         * Sets the value of the propertyName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPropertyName(String value) {
            this.propertyName = value;
        }

        /**
         * Gets the value of the propertyType property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getPropertyType() {
            return propertyType;
        }

        /**
         * Sets the value of the propertyType property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setPropertyType(Object value) {
            this.propertyType = value;
        }

        /**
         * Gets the value of the propertyBonus property.
         * 
         */
        public int getPropertyBonus() {
            return propertyBonus;
        }

        /**
         * Sets the value of the propertyBonus property.
         * 
         */
        public void setPropertyBonus(int value) {
            this.propertyBonus = value;
        }

        /**
         * Gets the value of the propertyTarget property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPropertyTarget() {
            return propertyTarget;
        }

        /**
         * Sets the value of the propertyTarget property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPropertyTarget(String value) {
            this.propertyTarget = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Kilograms" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="Lbs" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "kilograms",
        "lbs"
    })
    public static class Weight {

        @XmlElement(name = "Kilograms", namespace = "rgb.jaxb.character")
        protected double kilograms;
        @XmlElement(name = "Lbs", namespace = "rgb.jaxb.character")
        protected double lbs;

        /**
         * Gets the value of the kilograms property.
         * 
         */
        public double getKilograms() {
            return kilograms;
        }

        /**
         * Sets the value of the kilograms property.
         * 
         */
        public void setKilograms(double value) {
            this.kilograms = value;
        }

        /**
         * Gets the value of the lbs property.
         * 
         */
        public double getLbs() {
            return lbs;
        }

        /**
         * Sets the value of the lbs property.
         * 
         */
        public void setLbs(double value) {
            this.lbs = value;
        }

    }

}
