//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.06.22 at 12:39:58 BST 
//


package rpg.jaxb;


/**
 * Comment describing your root element
 * Java content class for ProtectiveItem element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Documents%20and%20Settings/Sven-Ivar%20Fjeld/Mine%20dokumenter/_Development/Java/GameMaster/xml/schemas/all.xsd line 35)
 * <p>
 * <pre>
 * &lt;element name="ProtectiveItem">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="ArmorShield" maxOccurs="unbounded">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="ACBonus" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="MaxDexBonus" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="ArmorCheckPenalty" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="ArcaneSpellFailure" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="Speed">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="ft30" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                               &lt;element name="ft20" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Weight">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="Kilograms" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                               &lt;element name="Lbs" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="SpecialProperties" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="PropertyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="PropertyType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="PropertyBonus" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                               &lt;element name="PropertyTarget" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 */
public interface ProtectiveItem
    extends javax.xml.bind.Element, rpg.jaxb.ProtectiveItemType
{


}
