//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.06.22 at 12:39:58 BST 
//


package rpg.jaxb;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Documents%20and%20Settings/Sven-Ivar%20Fjeld/Mine%20dokumenter/_Development/Java/GameMaster/xml/schemas/all.xsd line 288)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Damage">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Small">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="LowerBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="UpperBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Medium">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="LowerBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="UpperBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Critical">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CriticalMultiplier" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="LowerBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="UpperBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Weight">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Kilograms" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="Lbs" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BattleForm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SpecialProperties" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PropertyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PropertyType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="PropertyBonus" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="PropertyTarget" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RangeIncrement" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface WeaponType {


    /**
     * Slashing, Piercing or Bludgeoning
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getType();

    /**
     * Slashing, Piercing or Bludgeoning
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setType(java.lang.String value);

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link rpg.jaxb.WeaponType.WeightType}
     */
    rpg.jaxb.WeaponType.WeightType getWeight();

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link rpg.jaxb.WeaponType.WeightType}
     */
    void setWeight(rpg.jaxb.WeaponType.WeightType value);

    /**
     * Gets the value of the damage property.
     * 
     * @return
     *     possible object is
     *     {@link rpg.jaxb.WeaponType.DamageType}
     */
    rpg.jaxb.WeaponType.DamageType getDamage();

    /**
     * Sets the value of the damage property.
     * 
     * @param value
     *     allowed object is
     *     {@link rpg.jaxb.WeaponType.DamageType}
     */
    void setDamage(rpg.jaxb.WeaponType.DamageType value);

    /**
     * Gets the value of the critical property.
     * 
     * @return
     *     possible object is
     *     {@link rpg.jaxb.WeaponType.CriticalType}
     */
    rpg.jaxb.WeaponType.CriticalType getCritical();

    /**
     * Sets the value of the critical property.
     * 
     * @param value
     *     allowed object is
     *     {@link rpg.jaxb.WeaponType.CriticalType}
     */
    void setCritical(rpg.jaxb.WeaponType.CriticalType value);

    /**
     * Normal, Light Melee, One-Handed Melee, Two-Handed Melee, Ranged
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getBattleForm();

    /**
     * Normal, Light Melee, One-Handed Melee, Two-Handed Melee, Ranged
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setBattleForm(java.lang.String value);

    /**
     * Gets the value of the rangeIncrement property.
     * 
     */
    int getRangeIncrement();

    /**
     * Sets the value of the rangeIncrement property.
     * 
     */
    void setRangeIncrement(int value);

    /**
     * Gets the value of the SpecialProperties property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the SpecialProperties property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecialProperties().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link rpg.jaxb.WeaponType.SpecialPropertiesType}
     * 
     */
    java.util.List getSpecialProperties();

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getCategory();

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setCategory(java.lang.String value);

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getName();

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setName(java.lang.String value);


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Documents%20and%20Settings/Sven-Ivar%20Fjeld/Mine%20dokumenter/_Development/Java/GameMaster/xml/schemas/all.xsd line 314)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CriticalMultiplier" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="LowerBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="UpperBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface CriticalType {


        /**
         * Gets the value of the lowerBound property.
         * 
         */
        int getLowerBound();

        /**
         * Sets the value of the lowerBound property.
         * 
         */
        void setLowerBound(int value);

        /**
         * Gets the value of the criticalMultiplier property.
         * 
         */
        int getCriticalMultiplier();

        /**
         * Sets the value of the criticalMultiplier property.
         * 
         */
        void setCriticalMultiplier(int value);

        /**
         * Gets the value of the upperBound property.
         * 
         */
        int getUpperBound();

        /**
         * Sets the value of the upperBound property.
         * 
         */
        void setUpperBound(int value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Documents%20and%20Settings/Sven-Ivar%20Fjeld/Mine%20dokumenter/_Development/Java/GameMaster/xml/schemas/all.xsd line 292)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Small">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="LowerBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="UpperBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Medium">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="LowerBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="UpperBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface DamageType {


        /**
         * Gets the value of the medium property.
         * 
         * @return
         *     possible object is
         *     {@link rpg.jaxb.WeaponType.DamageType.MediumType}
         */
        rpg.jaxb.WeaponType.DamageType.MediumType getMedium();

        /**
         * Sets the value of the medium property.
         * 
         * @param value
         *     allowed object is
         *     {@link rpg.jaxb.WeaponType.DamageType.MediumType}
         */
        void setMedium(rpg.jaxb.WeaponType.DamageType.MediumType value);

        /**
         * Gets the value of the small property.
         * 
         * @return
         *     possible object is
         *     {@link rpg.jaxb.WeaponType.DamageType.SmallType}
         */
        rpg.jaxb.WeaponType.DamageType.SmallType getSmall();

        /**
         * Sets the value of the small property.
         * 
         * @param value
         *     allowed object is
         *     {@link rpg.jaxb.WeaponType.DamageType.SmallType}
         */
        void setSmall(rpg.jaxb.WeaponType.DamageType.SmallType value);


        /**
         * Java content class for anonymous complex type.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Documents%20and%20Settings/Sven-Ivar%20Fjeld/Mine%20dokumenter/_Development/Java/GameMaster/xml/schemas/all.xsd line 303)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="LowerBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="UpperBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface MediumType {


            /**
             * Gets the value of the lowerBound property.
             * 
             */
            int getLowerBound();

            /**
             * Sets the value of the lowerBound property.
             * 
             */
            void setLowerBound(int value);

            /**
             * Gets the value of the upperBound property.
             * 
             */
            int getUpperBound();

            /**
             * Sets the value of the upperBound property.
             * 
             */
            void setUpperBound(int value);

        }


        /**
         * Java content class for anonymous complex type.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Documents%20and%20Settings/Sven-Ivar%20Fjeld/Mine%20dokumenter/_Development/Java/GameMaster/xml/schemas/all.xsd line 295)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="LowerBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="UpperBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface SmallType {


            /**
             * Gets the value of the lowerBound property.
             * 
             */
            int getLowerBound();

            /**
             * Sets the value of the lowerBound property.
             * 
             */
            void setLowerBound(int value);

            /**
             * Gets the value of the upperBound property.
             * 
             */
            int getUpperBound();

            /**
             * Sets the value of the upperBound property.
             * 
             */
            void setUpperBound(int value);

        }

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Documents%20and%20Settings/Sven-Ivar%20Fjeld/Mine%20dokumenter/_Development/Java/GameMaster/xml/schemas/all.xsd line 342)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PropertyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PropertyType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="PropertyBonus" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="PropertyTarget" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface SpecialPropertiesType {


        /**
         * The target, e.g. Attck Bonus, Fortitude Save
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getPropertyTarget();

        /**
         * The target, e.g. Attck Bonus, Fortitude Save
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setPropertyTarget(java.lang.String value);

        /**
         * The type, eg. Luck, AC Bonus, Attack Bonus
         * 
         * @return
         *     possible object is
         *     {@link rpg.jaxb.AnyType}
         */
        rpg.jaxb.AnyType getPropertyType();

        /**
         * The type, eg. Luck, AC Bonus, Attack Bonus
         * 
         * @param value
         *     allowed object is
         *     {@link rpg.jaxb.AnyType}
         */
        void setPropertyType(rpg.jaxb.AnyType value);

        /**
         * Gets the value of the propertyBonus property.
         * 
         */
        int getPropertyBonus();

        /**
         * Sets the value of the propertyBonus property.
         * 
         */
        void setPropertyBonus(int value);

        /**
         * The name of the property, e.g. Holy Attack
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getPropertyName();

        /**
         * The name of the property, e.g. Holy Attack
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setPropertyName(java.lang.String value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Documents%20and%20Settings/Sven-Ivar%20Fjeld/Mine%20dokumenter/_Development/Java/GameMaster/xml/schemas/all.xsd line 323)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Kilograms" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="Lbs" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface WeightType {


        /**
         * Gets the value of the kilograms property.
         * 
         */
        double getKilograms();

        /**
         * Sets the value of the kilograms property.
         * 
         */
        void setKilograms(double value);

        /**
         * Gets the value of the lbs property.
         * 
         */
        double getLbs();

        /**
         * Sets the value of the lbs property.
         * 
         */
        void setLbs(double value);

    }

}
