//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.06.22 at 12:39:58 BST 
//


package rpg.jaxb;


/**
 * Java content class for Weapon element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Documents%20and%20Settings/Sven-Ivar%20Fjeld/Mine%20dokumenter/_Development/Java/GameMaster/xml/schemas/all.xsd line 287)
 * <p>
 * <pre>
 * &lt;element name="Weapon">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="Damage">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Small">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="LowerBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                               &lt;element name="UpperBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Medium">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="LowerBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                               &lt;element name="UpperBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="Critical">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="CriticalMultiplier" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="LowerBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="UpperBound" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="Weight">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Kilograms" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                     &lt;element name="Lbs" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="BattleForm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="SpecialProperties" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="PropertyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="PropertyType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                     &lt;element name="PropertyBonus" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="PropertyTarget" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="RangeIncrement" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 */
public interface Weapon
    extends javax.xml.bind.Element, rpg.jaxb.WeaponType
{


}
