//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package rpg.v4.middleware.jaxb;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Target">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="My"/>
 *               &lt;enumeration value="CurrentAttacker"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{rgb.jaxb.character}V4_StateID"/>
 *         &lt;element name="Is">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="String" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="GreaterThan" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{rgb.jaxb.character}V4_Modifier"/>
 *         &lt;element ref="{rgb.jaxb.character}V4_CheckCombiner" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "target",
    "v4StateID",
    "is",
    "v4Modifier",
    "v4CheckCombiner"
})
@XmlRootElement(name = "V4_EntityCheck")
public class V4EntityCheck {

    @XmlElement(name = "Target", required = true)
    protected String target;
    @XmlElement(name = "V4_StateID", required = true)
    protected String v4StateID;
    @XmlElement(name = "Is", required = true)
    protected V4EntityCheck.Is is;
    @XmlElement(name = "V4_Modifier", required = true)
    protected V4Modifier v4Modifier;
    @XmlElement(name = "V4_CheckCombiner")
    protected List<V4CheckCombiner> v4CheckCombiner;

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarget(String value) {
        this.target = value;
    }

    /**
     * Gets the value of the v4StateID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getV4StateID() {
        return v4StateID;
    }

    /**
     * Sets the value of the v4StateID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setV4StateID(String value) {
        this.v4StateID = value;
    }

    /**
     * Gets the value of the is property.
     * 
     * @return
     *     possible object is
     *     {@link V4EntityCheck.Is }
     *     
     */
    public V4EntityCheck.Is getIs() {
        return is;
    }

    /**
     * Sets the value of the is property.
     * 
     * @param value
     *     allowed object is
     *     {@link V4EntityCheck.Is }
     *     
     */
    public void setIs(V4EntityCheck.Is value) {
        this.is = value;
    }

    /**
     * Gets the value of the v4Modifier property.
     * 
     * @return
     *     possible object is
     *     {@link V4Modifier }
     *     
     */
    public V4Modifier getV4Modifier() {
        return v4Modifier;
    }

    /**
     * Sets the value of the v4Modifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link V4Modifier }
     *     
     */
    public void setV4Modifier(V4Modifier value) {
        this.v4Modifier = value;
    }

    /**
     * Gets the value of the v4CheckCombiner property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the v4CheckCombiner property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getV4CheckCombiner().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link V4CheckCombiner }
     * 
     * 
     */
    public List<V4CheckCombiner> getV4CheckCombiner() {
        if (v4CheckCombiner == null) {
            v4CheckCombiner = new ArrayList<V4CheckCombiner>();
        }
        return this.v4CheckCombiner;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="String" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="GreaterThan" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "string",
        "greaterThan"
    })
    public static class Is {

        @XmlElement(name = "String")
        protected List<Object> string;
        @XmlElement(name = "GreaterThan")
        protected Object greaterThan;

        /**
         * Gets the value of the string property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the string property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getString().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * 
         * 
         */
        public List<Object> getString() {
            if (string == null) {
                string = new ArrayList<Object>();
            }
            return this.string;
        }

        /**
         * Gets the value of the greaterThan property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getGreaterThan() {
            return greaterThan;
        }

        /**
         * Sets the value of the greaterThan property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setGreaterThan(Object value) {
            this.greaterThan = value;
        }

    }

}
